#!/bin/sh
cat 10_top.j2

awk '{
print "{{       render_option(\""$1"\", match[\""$1"\"], true) -}}"
}' < options_body

cat 20_after_match.j2

awk '{
print "{{       render_option(\""$1"\", host[\""$1"\"], true) -}}"
}' < options_body

cat 30_after_host.j2

awk '{
print "{{ body_option(\""$1"\", ssh_"$1") -}}"
}' < options_body

cat 40_bottom.j2
