name: Ansible CI
on: [push, pull_request]

env:
  ANSIBLE_INJECT_FACT_VARS: "false"

jobs:
  test:
    if: |
      !((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[citest_skip]')) ||
        (github.event_name == 'push' && contains(github.event.head_commit.message, '[citest_skip]')))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_image:
          - alpine:latest
          - quay.io/centos/centos:stream8
          - quay.io/centos/centos:stream9
          - quay.io/centos/centos:stream10
          - debian:bullseye
          - debian:bookworm
          - debian:latest
          - fedora:latest
          - ubuntu:22.04
          - ubuntu:24.04
          - ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Test Ansible SSH Role
        uses: Jakuje/check-ansible-action@f64d87a5598747f49294b37d7302083afbc15c76
        with:
          image: ${{ matrix.os_image }}
          group: local
          hosts: localhost
          targets: "tests/tests_*.yml"
